[package]
name = "farfs"
version = "0.1.0"
edition = "2024"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1

[dependencies]
bitfield = "0.19.5"
bytemuck = { version = "1.25.2", features = ["derive"] }
varint-rs = { version = "2.2.1", default-features = false, features = ["std"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.189"